=== AlekseiIvshin/03_JAXB_StAX_XML_Parsing/resources/products.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!-- Root -->
	<xs:element name="categories">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="category" type="categoryType" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- Type of category -->
	<xs:complexType name="categoryType">
		<xs:sequence>
			<!-- Set of subcategories -->
			<xs:element name="subcategories" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="subcategory" type="subcategoryType" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<!-- Type of subcategory -->
	<xs:complexType name="subcategoryType">
		<xs:sequence>
			<!-- Set of products -->
			<xs:element name="products" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="product" type="productType" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<!-- Type of product -->
	<xs:complexType name="productType">
		<xs:sequence>
			<!-- Manufactured by ... -->
			<xs:element name="manufacturer" type="xs:string"/>
			<!-- Model -->
			<xs:element name="model">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[a-zA-Z][a-zA-Z][0-9][0-9][0-9]"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<!-- Release date -->
			<xs:element name="date">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="((0[1-9])|([1-2][0-9])|(3[0-1]))-((0[1-9])|(1[0-2]))-[0-9]{4}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<!-- Color -->
			<xs:element name="color" default="none">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="(((\w+)|(#[0-9a-fA-F]{6})),?)*"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<!-- Price -->
			<xs:element name="price" type="xs:decimal"/>
			<!-- Count -->
			<xs:element name="count" type="xs:nonNegativeInteger" default="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== AlekseiIvshin/03_JAXB_StAX_XML_Parsing/resources/resultStAX.xml
<?xml version="1.0" encoding="UTF-8"?><categories xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="products.xsd">
	<category name="Периферия и оргтехника">
		<subcategories>
			<subcategory name="Сканеры">
				
					
					<product>
						<manufacturer>HP</manufacturer>
						<model>SJ200</model>
						<date>01-05-2014</date>
						<color>grey,black</color>
						<price>2950.00</price>
						<count>0</count>
					</product>
				</subcategory>
			</subcategories>
			<subcategory name="Мыши">
				
					
					<product>
						<manufacturer>A4Tech</manufacturer>
						<model>VM007</model>
						<date>30-05-2014</date>
						<color>grey,#2323a2,red,#2ff3ac</color>
						<price>1350.00</price>
						<count>2</count>
					</product>
					<product>
						<manufacturer>A4Tech</manufacturer>
						<model>GN713</model>
						<date>20-11-2013</date>
						<color>blue,#000000</color>
						<price>590.00</price>
						<count>3</count>
					</product>
					<product>
						<manufacturer>A4Tech</manufacturer>
						<model>GF555</model>
						<date>01-05-2014</date>
						<color>#0ca92b,pink,black</color>
						<price>610.00</price>
						<count>0</count>
					</product>
				</subcategory>
			</category>
		</categories>

=== AlekseiIvshin/03_JAXB_StAX_XML_Parsing/resources/products.xml
<?xml version="1.0" encoding="UTF-8"?>
<categories 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="products.xsd">
	<category name="Периферия и оргтехника">
		<subcategories>
			<subcategory name="Сканеры">
				<products>
					<product>
						<manufacturer>Canon</manufacturer>
						<model>FF900</model>
						<date>20-01-2014</date>
						<color>grey,black</color>
						<price>9950.00</price>
						<count>3</count>
					</product>
					<product>
						<manufacturer>HP</manufacturer>
						<model>SJ200</model>
						<date>01-05-2014</date>
						<color>grey,black</color>
						<price>2950.00</price>
						<count>0</count>
					</product>
				</products>
			</subcategory>
			<subcategory name="Мыши">
				<products>
					<product>
						<manufacturer>DNS</manufacturer>
						<model>Gv151</model>
						<date>20-07-2014</date>
						<color>black</color>
						<price>720.00</price>
						<count>10</count>
					</product>
					<product>
						<manufacturer>A4Tech</manufacturer>
						<model>VM007</model>
						<date>30-05-2014</date>
						<color>grey,#2323a2,red,#2ff3ac</color>
						<price>1350.00</price>
						<count>2</count>
					</product>
					<product>
						<manufacturer>A4Tech</manufacturer>
						<model>GN713</model>
						<date>20-11-2013</date>
						<color>blue,#000000</color>
						<price>590.00</price>
						<count>3</count>
					</product>
					<product>
						<manufacturer>A4Tech</manufacturer>
						<model>GF555</model>
						<date>01-05-2014</date>
						<color>#0ca92b,pink,black</color>
						<price>610.00</price>
						<count>0</count>
					</product>
				</products>
			</subcategory>
		</subcategories>
	</category>
	
	
	<category name="Принтеры">
		<subcategories>
			<subcategory name="Лазерные">
				<products>
					<product>
						<manufacturer>Xerox</manufacturer>
						<model>DN233</model>
						<date>20-12-2014</date>
						<color>white,#00da21</color>
						<price>9790.00</price>
						<count>3</count>
					</product>
				</products>
			</subcategory>
			<subcategory  name="Струйные">
				<products>
					<product>
						<manufacturer>Canon</manufacturer>
						<model>IP270</model>
						<date>22-11-2014</date>
						<color>black</color>
						<price>1350.0</price>
						<count>3</count>
					</product>
					<product>
						<manufacturer>Epson</manufacturer>
						<model>Li300</model>
						<date>20-07-2014</date>
						<color>red</color>
						<price>21990</price>
						<count>1</count>
					</product>
				</products>
			</subcategory>
		</subcategories>
	</category>
</categories>
